# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'puma', '~> 4.1'
gem 'rack-cors'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop-rails'
  gem 'solargraph'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # pry-patches
  gem 'awesome_print'
  gem 'coderay'
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-theme'
  # tests
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.5'
end

# gem 'bcrypt', '~> 3.1.7'
# gem 'jwt'

#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'
#db-adapter
gem 'mysql2'